# Generated by Django 5.1.3 on 2025-06-12 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PontoMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMedidor', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_medicao', to=settings.AUTH_USER_MODEL)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontoMedida', to='caudais.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ponto_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='caudais.pontomedida')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField()),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_Processadas', to='caudais.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='caudais.serie')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)'), ('raw', 'Raw')], max_length=20)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total', models.FloatField()),
                ('media', models.FloatField()),
                ('contagem', models.IntegerField()),
                ('minWhisker', models.FloatField(blank=True, null=True)),
                ('maxWhisker', models.FloatField(blank=True, null=True)),
                ('medianaMensal', models.FloatField(blank=True, null=True)),
                ('q1', models.FloatField(blank=True, null=True)),
                ('q3', models.FloatField(blank=True, null=True)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatisticasMensais', to='caudais.serie')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)'), ('raw', 'Raw')], max_length=20)),
                ('ano', models.IntegerField()),
                ('total', models.FloatField()),
                ('media', models.FloatField()),
                ('contagem', models.IntegerField()),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatisticasAnuais', to='caudais.serie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('ponto_medida', 'nome'), name='unique_serie_por_ponto'),
        ),
        migrations.AlterUniqueTogether(
            name='medicaoprocessada',
            unique_together={('metodo', 'timestamp', 'serie')},
        ),
        migrations.AlterUniqueTogether(
            name='medicao',
            unique_together={('timestamp', 'serie')},
        ),
        migrations.AlterUniqueTogether(
            name='estatisticamensal',
            unique_together={('metodo', 'ano', 'mes', 'serie')},
        ),
        migrations.AlterUniqueTogether(
            name='estatisticaanual',
            unique_together={('metodo', 'ano', 'serie')},
        ),
    ]
